[package]
name = "variant_generation"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
image = { version = "0.25.9", features = ["png"] }
log = "0.4.29"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.146"
